### ISSUE TITLE
opencv-python version mismatch between wild-visual-navigation and stego

### ISSUE THREAD

**Issue by AfonsoEloy** [leggedrobotics/wild_visual_navigation#312] opened 2024-11-27 15:44 UTC
Hi guys! First of all, thank you for the great work.

I am following the docker setup instructions on a 20.04 Noetic machine. Everything appears to work fine during the build and first setup, except this error that pops up:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
wild-visual-navigation 0.0.1 requires opencv-python==4.2.0.34, but you have opencv-python 4.6.0.66 which is incompatible.`

If, instead, I try to force the installation of 4.2.0.34, then I receive a similar error complaining that stego requires >= 4.6.

Am I doing something wrong or is there something wrong in the setup files?

Thanks in advance!

**Comment by mmattamala** [comment] 2024-11-27 20:00
Hi Afonso, thanks for your interest in our paper!

We're a bit busy at the moment, but I can take a look early next week if that works. I agree that there could be a dependency mismatch that we oversaw. Pinning the versions might solve it but I'll need to test it to see if we need to propagate corrections to other repos.

I hope that works, but let me know if you are in a rush

**Comment by AfonsoEloy** [comment] 2024-11-28 18:45
We are also on a schedule, but early next week works!

Will be waiting for updates. Thanks!

**Comment by mmattamala** [comment] 2024-11-29 11:01
Hi @AfonsoEloy , I just pushed a minor fix in the `self_supervised_segmentation` repo to relax the opencv version, which was set to >=4.6. I tested it locally on my laptop and it works as intended, let me know if the problem persists.

**Comment by AfonsoEloy** [comment] 2024-11-29 23:00
Hi @mmattamala. Your fix solved the issue, thanks! Final set of questions:

1. Is the docker container as-is suitable to run WVN with a dataset of real data, or only for the simulation demo?
2. The datasets we are collecting only have images from a single RGB-D front-facing camera (realsense d435i). Considering I see multiple front and rear cameras being referenced in your config files, can the system work with only one?
3. Aside from the images, are there any mandatory inputs that must come from a specific platform like ANYmal, or do other legged robots work (such as the Unitree Go1 EDU, which we are using).

**Comment by mmattamala** [comment] 2024-11-29 23:20
Awesome, glad to know it worked. Regarding your questions:

1. The docker container should work with real data too, unless there are specific packages and dependencies required by your data (e.g., message definitions). I should have added a devcontainer config file to make the development easier (so you work with VSCode within the container, but I learned this after I prepared this docker). I could do it next week if you think it might help you
2. That's absolutely possible and it's actually the configuration we used for our RSS paper. The multi-camera feature was added in our extended paper but it still processes one camera at a time
3. If you inspect the Jackal simulation example more closely, it only requires the image, tf data with an odometry source (to generate the supervision signal via the reprojected path), and a velocity command. We did not use any raw proprioceptive signal (e.g., IMU or joint encoders). Jonas has a follow up paper using proprioception to estimate physical terrain properties: https://leggedrobotics.github.io/identifying_terrain_physical_parameters_webpage/

**Comment by AfonsoEloy** [comment] 2024-12-02 16:09
Don't worry about the devcontainer, I can manage without it. I'll spend the next few days working on integrating your system with our data. Your help has been incredibly valuable -- thank you!

**Comment by mmattamala** [comment] 2024-12-03 10:00
Awesome, you're welcome! I look forward to seeing how WVN works with your system :)
I'll close the issue for now but feel free to reopen it if new problems arise.

**Closed as completed by mmattamala** 2024-12-03 10:00 UTC

**Comment by fwx20020105** [comment] 2026-05-25 06:48
> Hi guys! First of all, thank you for the great work.大家好！首先，感谢你们的精彩工作。
> 
> I am following the docker setup instructions on a 20.04 Noetic machine. Everything appears to work fine during the build and first setup, except this error that pops up:我正在按照 Docker 设置说明在一台 20.04 Noetic 机器上操作。在构建和首次设置过程中，一切似乎都正常，除了弹出这个错误：
> 
> `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. wild-visual-navigation 0.0.1 requires opencv-python==4.2.0.34, but you have opencv-python 4.6.0.66 which is incompatible.`错误：PIP 的依赖解析器目前未涵盖所有已安装的软件包。这种行为是以下依赖冲突的根源。wild-visual-navigation 0.0.1 需要 opencv-python==4.2.0.34，但你有 opencv-python 4.6.0.66，不兼容。
> 
> If, instead, I try to force the installation of 4.2.0.34, then I receive a similar error complaining that stego requires >= 4.6.如果我尝试强制安装4.2.0.34，就会收到类似错误，抱怨剑斗需要>= 4.6。
> 
> Am I doing something wrong or is there something wrong in the setup files?是作哪里不对，还是安装文件里有问题？
> 
> Thanks in advance!  提前感谢大家！

I'm sorry to bother you.I found that the Google Drive links for checkpoints and rosbags are returning 404 errors. I was wondering if you still have the relevant field rosbag files available. If so, could you please send them to my email address: 1035664828@qq.com? I would be extremely grateful.
